import { SelectOption } from '../types/forms';

export const COUNTRIES: SelectOption[] = [
  { label: 'Afghanistan', id: 'Afghanistan' },
  { label: 'Albania', id: 'Albania' },
  { label: 'Algeria', id: 'Algeria' },
  { label: 'Andorra', id: 'Andorra' },
  { label: 'Angola', id: 'Angola' },
  { label: 'Antigua and Barbuda', id: 'Antigua and Barbuda' },
  { label: 'Argentina', id: 'Argentina' },
  { label: 'Armenia', id: 'Armenia' },
  { label: 'Australia', id: 'Australia' },
  { label: 'Austria', id: 'Austria' },
  { label: 'Azerbaijan', id: 'Azerbaijan' },
  { label: 'Bahamas', id: 'Bahamas' },
  { label: 'Bahrain', id: 'Bahrain' },
  { label: 'Bangladesh', id: 'Bangladesh' },
  { label: 'Barbados', id: 'Barbados' },
  { label: 'Belarus', id: 'Belarus' },
  { label: 'Belgium', id: 'Belgium' },
  { label: 'Belize', id: 'Belize' },
  { label: 'Benin', id: 'Benin' },
  { label: 'Bhutan', id: 'Bhutan' },
  { label: 'Bolivia', id: 'Bolivia' },
  { label: 'Bosnia and Herzegovina', id: 'Bosnia and Herzegovina' },
  { label: 'Botswana', id: 'Botswana' },
  { label: 'Brazil', id: 'Brazil' },
  { label: 'Brunei', id: 'Brunei' },
  { label: 'Bulgaria', id: 'Bulgaria' },
  { label: 'Burkina Faso', id: 'Burkina Faso' },
  { label: 'Burundi', id: 'Burundi' },
  { label: 'Cambodia', id: 'Cambodia' },
  { label: 'Cameroon', id: 'Cameroon' },
  { label: 'Canada', id: 'Canada' },
  { label: 'Cape Verde', id: 'Cape Verde' },
  { label: 'Central African Republic', id: 'Central African Republic' },
  { label: 'Chad', id: 'Chad' },
  { label: 'Chile', id: 'Chile' },
  { label: 'China', id: 'China' },
  { label: 'Colombia', id: 'Colombia' },
  { label: 'Comoros', id: 'Comoros' },
  { label: 'Congo', id: 'Congo' },
  { label: 'Costa Rica', id: 'Costa Rica' },
  { label: 'Croatia', id: 'Croatia' },
  { label: 'Cuba', id: 'Cuba' },
  { label: 'Cyprus', id: 'Cyprus' },
  { label: 'Czech Republic', id: 'Czech Republic' },
  { label: 'Denmark', id: 'Denmark' },
  { label: 'Djibouti', id: 'Djibouti' },
  { label: 'Dominica', id: 'Dominica' },
  { label: 'Dominican Republic', id: 'Dominican Republic' },
  { label: 'Ecuador', id: 'Ecuador' },
  { label: 'Egypt', id: 'Egypt' },
  { label: 'El Salvador', id: 'El Salvador' },
  { label: 'Equatorial Guinea', id: 'Equatorial Guinea' },
  { label: 'Eritrea', id: 'Eritrea' },
  { label: 'Estonia', id: 'Estonia' },
  { label: 'Eswatini', id: 'Eswatini' },
  { label: 'Ethiopia', id: 'Ethiopia' },
  { label: 'Fiji', id: 'Fiji' },
  { label: 'Finland', id: 'Finland' },
  { label: 'France', id: 'France' },
  { label: 'Gabon', id: 'Gabon' },
  { label: 'Gambia', id: 'Gambia' },
  { label: 'Georgia', id: 'Georgia' },
  { label: 'Germany', id: 'Germany' },
  { label: 'Ghana', id: 'Ghana' },
  { label: 'Greece', id: 'Greece' },
  { label: 'Grenada', id: 'Grenada' },
  { label: 'Guatemala', id: 'Guatemala' },
  { label: 'Guinea', id: 'Guinea' },
  { label: 'Guinea-Bissau', id: 'Guinea-Bissau' },
  { label: 'Guyana', id: 'Guyana' },
  { label: 'Haiti', id: 'Haiti' },
  { label: 'Honduras', id: 'Honduras' },
  { label: 'Hungary', id: 'Hungary' },
  { label: 'Iceland', id: 'Iceland' },
  { label: 'India', id: 'India' },
  { label: 'Indonesia', id: 'Indonesia' },
  { label: 'Iran', id: 'Iran' },
  { label: 'Iraq', id: 'Iraq' },
  { label: 'Ireland', id: 'Ireland' },
  { label: 'Israel', id: 'Israel' },
  { label: 'Italy', id: 'Italy' },
  { label: 'Jamaica', id: 'Jamaica' },
  { label: 'Japan', id: 'Japan' },
  { label: 'Jordan', id: 'Jordan' },
  { label: 'Kazakhstan', id: 'Kazakhstan' },
  { label: 'Kenya', id: 'Kenya' },
  { label: 'Kiribati', id: 'Kiribati' },
  { label: 'Kuwait', id: 'Kuwait' },
  { label: 'Kyrgyzstan', id: 'Kyrgyzstan' },
  { label: 'Laos', id: 'Laos' },
  { label: 'Latvia', id: 'Latvia' },
  { label: 'Lebanon', id: 'Lebanon' },
  { label: 'Lesotho', id: 'Lesotho' },
  { label: 'Liberia', id: 'Liberia' },
  { label: 'Libya', id: 'Libya' },
  { label: 'Liechtenstein', id: 'Liechtenstein' },
  { label: 'Lithuania', id: 'Lithuania' },
  { label: 'Luxembourg', id: 'Luxembourg' },
  { label: 'Madagascar', id: 'Madagascar' },
  { label: 'Malawi', id: 'Malawi' },
  { label: 'Malaysia', id: 'Malaysia' },
  { label: 'Maldives', id: 'Maldives' },
  { label: 'Mali', id: 'Mali' },
  { label: 'Malta', id: 'Malta' },
  { label: 'Marshall Islands', id: 'Marshall Islands' },
  { label: 'Mauritania', id: 'Mauritania' },
  { label: 'Mauritius', id: 'Mauritius' },
  { label: 'Mexico', id: 'Mexico' },
  { label: 'Micronesia', id: 'Micronesia' },
  { label: 'Moldova', id: 'Moldova' },
  { label: 'Monaco', id: 'Monaco' },
  { label: 'Mongolia', id: 'Mongolia' },
  { label: 'Montenegro', id: 'Montenegro' },
  { label: 'Morocco', id: 'Morocco' },
  { label: 'Mozambique', id: 'Mozambique' },
  { label: 'Myanmar', id: 'Myanmar' },
  { label: 'Namibia', id: 'Namibia' },
  { label: 'Nauru', id: 'Nauru' },
  { label: 'Nepal', id: 'Nepal' },
  { label: 'Netherlands', id: 'Netherlands' },
  { label: 'New Zealand', id: 'New Zealand' },
  { label: 'Nicaragua', id: 'Nicaragua' },
  { label: 'Niger', id: 'Niger' },
  { label: 'Nigeria', id: 'Nigeria' },
  { label: 'North Korea', id: 'North Korea' },
  { label: 'North Macedonia', id: 'North Macedonia' },
  { label: 'Norway', id: 'Norway' },
  { label: 'Oman', id: 'Oman' },
  { label: 'Pakistan', id: 'Pakistan' },
  { label: 'Palau', id: 'Palau' },
  { label: 'Panama', id: 'Panama' },
  { label: 'Papua New Guinea', id: 'Papua New Guinea' },
  { label: 'Paraguay', id: 'Paraguay' },
  { label: 'Peru', id: 'Peru' },
  { label: 'Philippines', id: 'Philippines' },
  { label: 'Poland', id: 'Poland' },
  { label: 'Portugal', id: 'Portugal' },
  { label: 'Qatar', id: 'Qatar' },
  { label: 'Romania', id: 'Romania' },
  { label: 'Russia', id: 'Russia' },
  { label: 'Rwanda', id: 'Rwanda' },
  { label: 'Saint Kitts and Nevis', id: 'Saint Kitts and Nevis' },
  { label: 'Saint Lucia', id: 'Saint Lucia' },
  { label: 'Saint Vincent and the Grenadines', id: 'Saint Vincent and the Grenadines' },
  { label: 'Samoa', id: 'Samoa' },
  { label: 'San Marino', id: 'San Marino' },
  { label: 'Sao Tome and Principe', id: 'Sao Tome and Principe' },
  { label: 'Saudi Arabia', id: 'Saudi Arabia' },
  { label: 'Senegal', id: 'Senegal' },
  { label: 'Serbia', id: 'Serbia' },
  { label: 'Seychelles', id: 'Seychelles' },
  { label: 'Sierra Leone', id: 'Sierra Leone' },
  { label: 'Singapore', id: 'Singapore' },
  { label: 'Slovakia', id: 'Slovakia' },
  { label: 'Slovenia', id: 'Slovenia' },
  { label: 'Solomon Islands', id: 'Solomon Islands' },
  { label: 'Somalia', id: 'Somalia' },
  { label: 'South Africa', id: 'South Africa' },
  { label: 'South Korea', id: 'South Korea' },
  { label: 'South Sudan', id: 'South Sudan' },
  { label: 'Spain', id: 'Spain' },
  { label: 'Sri Lanka', id: 'Sri Lanka' },
  { label: 'Sudan', id: 'Sudan' },
  { label: 'Suriname', id: 'Suriname' },
  { label: 'Sweden', id: 'Sweden' },
  { label: 'Switzerland', id: 'Switzerland' },
  { label: 'Syria', id: 'Syria' },
  { label: 'Tajikistan', id: 'Tajikistan' },
  { label: 'Tanzania', id: 'Tanzania' },
  { label: 'Thailand', id: 'Thailand' },
  { label: 'Timor-Leste', id: 'Timor-Leste' },
  { label: 'Togo', id: 'Togo' },
  { label: 'Tonga', id: 'Tonga' },
  { label: 'Trinidad and Tobago', id: 'Trinidad and Tobago' },
  { label: 'Tunisia', id: 'Tunisia' },
  { label: 'Turkey', id: 'Turkey' },
  { label: 'Turkmenistan', id: 'Turkmenistan' },
  { label: 'Tuvalu', id: 'Tuvalu' },
  { label: 'Uganda', id: 'Uganda' },
  { label: 'Ukraine', id: 'Ukraine' },
  { label: 'United Arab Emirates', id: 'United Arab Emirates' },
  { label: 'United Kingdom', id: 'United Kingdom' },
  { label: 'United States', id: 'United States' },
  { label: 'Uruguay', id: 'Uruguay' },
  { label: 'Uzbekistan', id: 'Uzbekistan' },
  { label: 'Vanuatu', id: 'Vanuatu' },
  { label: 'Vatican City', id: 'Vatican City' },
  { label: 'Venezuela', id: 'Venezuela' },
  { label: 'Vietnam', id: 'Vietnam' },
  { label: 'Yemen', id: 'Yemen' },
  { label: 'Zambia', id: 'Zambia' },
  { label: 'Zimbabwe', id: 'Zimbabwe' },
];
