import { Users, Activity, Clock, MessageSquare, Bot, Target } from 'lucide-react';
import { AnalyticsMetrics } from '../types/analytics';

interface StatisticsCardsProps {
  metrics: AnalyticsMetrics;
}

export function StatisticsCards({ metrics }: StatisticsCardsProps) {
  const formatSessionTime = (minutes: number) => {
    if (minutes < 60) {
      return `${minutes}m`;
    }
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  };

  interface StatCard {
    title: string;
    value: string;
    description: string;
    icon: any;
    color: string;
    lightColor: string;
    textColor: string;
    subValue?: string;
  }

  const cards: StatCard[] = [
    {
      title: 'Total Sessions',
      value: metrics.totalSessions.toLocaleString(),
      description: 'User interactions with the platform',
      icon: Activity,
      color: 'bg-blue-500',
      lightColor: 'bg-blue-50',
      textColor: 'text-blue-600',
    },
    {
      title: 'Total Unique Customers',
      value: metrics.uniqueCustomers.toLocaleString(),
      description: 'Distinct individuals who used the platform',
      icon: Users,
      color: 'bg-purple-500',
      lightColor: 'bg-purple-50',
      textColor: 'text-purple-600',
    },
    {
      title: 'Avg Session Time',
      value: formatSessionTime(metrics.avgSessionTime),
      description: 'Average time users spend per session (minutes)',
      icon: Clock,
      color: 'bg-green-500',
      lightColor: 'bg-green-50',
      textColor: 'text-green-600',
    },
    {
      title: 'Total Messages by Users',
      value: metrics.totalUserMessages.toLocaleString(),
      description: 'Messages sent by customers',
      icon: MessageSquare,
      color: 'bg-orange-500',
      lightColor: 'bg-orange-50',
      textColor: 'text-orange-600',
    },
    {
      title: 'AI Responses',
      value: metrics.totalAiResponses.toLocaleString(),
      description: 'Messages generated by AI',
      icon: Bot,
      color: 'bg-cyan-500',
      lightColor: 'bg-cyan-50',
      textColor: 'text-cyan-600',
    },
    {
      title: 'Total Leads',
      value: metrics.totalLeads.toLocaleString(),
      description: 'Captured leads from interactions',
      icon: Target,
      color: 'bg-pink-500',
      lightColor: 'bg-pink-50',
      textColor: 'text-pink-600',
    },
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {cards.map((card, index) => {
        const Icon = card.icon;
        return (
          <div
            key={index}
            className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:shadow-md transition-all hover:-translate-y-1 duration-200"
          >
            <div className="flex items-start justify-between mb-3">
              <div className={`w-12 h-12 ${card.lightColor} rounded-lg flex items-center justify-center`}>
                <Icon className={`w-6 h-6 ${card.textColor}`} />
              </div>
            </div>

            <div className="space-y-1">
              <h4 className="text-xs font-medium text-gray-500 uppercase tracking-wide">
                {card.title}
              </h4>
              <div className="flex items-baseline gap-2">
                <p className="text-2xl font-bold text-gray-900">{card.value}</p>
              </div>
              {card.subValue && (
                <p className="text-xs text-gray-600 font-medium">{card.subValue}</p>
              )}
              <p className="text-xs text-gray-500">{card.description}</p>
            </div>
          </div>
        );
      })}
    </div>
  );
}
